### ISSUE TITLE
Replace USB LAN Adapter and USB Hub with a cheaper eBay option.

### ISSUE THREAD

**Issue by akisblack** [bloodythorn/wiihacks-wiki#20]
I think it'd be a good idea to replace the USB LAN Adapter and USB Hub in the amazon page with this cheaper alternative. https://www.ebay.com/itm/233080282107 . I have it, and it works pretty well.

**Comment by Odyssey346** [comment]
🤡

**Comment by bloodythorn** [comment]
Nice, now I have you guys harassing our community Wiki.

**Comment by bloodythorn** [comment]
@akisblack I'm going to ask you this once. Leave my and my community alone. If you do not, I will start leveraging these platforms anti-harassing stances to direct them at you and your group of bulllies.
